error: Allow telex_error structures to be chained
Functions that may return multiple errors have to use a list or some
other container type because telex_error structures cannot be chained.

This commit adds a `next` member to `struct telex_error`, allowing
functions to return multiple errors without using another data
structure.